In [1]:
import numpy as np
import pandas as pd

In [2]:
PATH = "C:\\Users\\User\\Desktop\\CSVD_case.csv"

In [10]:
df = pd.read_csv(PATH, encoding = 'big5')

In [11]:
df = df.rename(columns={'Unnamed: 0': 'name'})

In [16]:
df.head(4)

name        No  total  lacune  microbleeds  PVS  WMH  frontal_mean  \
0   王明錦  16976407      3       1            2   10    3      0.013949   
1   林東龍    126690      4       5           15    3    3      0.000937   
2  黃范勤金  17085009      3       0           15    4    3      0.032223   
3   黃龍山  15060036      3       3            3    5    3      0.004575   

   Parietal_mean   WM_mean   CH_mean   BG_mean   TH_mean   GM_mean  total_mean  
0       0.017570  0.015760  0.033537  0.031380  0.011507  0.025475    0.020617  
1       0.001337  0.001137  0.000927  0.006990  0.000860  0.002926    0.002031  
2       0.102379  0.055608  0.049664  0.067837  0.018161  0.045221    0.050414  
3       0.096088  0.050331  0.036669  0.075415  0.027230  0.046438    0.048385

In [26]:
data = df.values[:,2:]

In [23]:
lacune = np.unique(df.lacune.values)
microbleeds = np.unique(df.microbleeds.values)
PVS = np.unique(df.PVS.values)
WMH = np.unique(df.WMH.values)
total = np.unique(df.total.values)

In [38]:
result_mean = []
result_std = []
criteria_list = []
for total_score in total:
    for lacune_num in lacune:
        for micro_num in microbleeds:
            for PVS_num in PVS:
                for WMH_num in WMH:
                    criteria_list.append([total_score, lacune_num, micro_num, PVS_num, WMH_num])
                    criteria = (data[:,0]>total_score) & (data[:,1]>lacune_num) & (data[:,2]>micro_num) & (data[:,3]>PVS_num) & (data[:,4]>WMH_num)
                    class1 = np.array(data[criteria][:,5:],dtype=np.float64)
                    class2 =  np.array(data[criteria == False][:,5:],dtype=np.float64)
                    
                    class1_mean = np.mean(class1, axis=0)
                    class1_std = np.std(class1, axis=0)
                    class2_mean = np.mean(class2, axis=0)
                    class2_std = np.std(class2, axis=0)
                    
                    result_mean.append([class1_mean, class2_mean])
                    result_std.append([class1_std, class2_std])
                    

D:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
D:\Anaconda\lib\site-packages\numpy\core\_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
D:\Anaconda\lib\site-packages\numpy\core\_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
D:\Anaconda\lib\site-packages\numpy\core\_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
D:\Anaconda\lib\site-packages\numpy\core\_methods.py:207: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)


In [39]:
for cri in range(len(criteria_list)):
    for Ki_loc in range(8):
        if abs(result_mean[0][Ki_loc]-result_mean[1][Ki_loc])

[[array([0.01668571, 0.03759392, 0.03105106, 0.04394247, 0.06411194,
         0.02567975, 0.04457805, 0.03781456]),
  array([0.0056281 , 0.01653198, 0.01099938, 0.01143043, 0.02578757,
         0.01392144, 0.01959599, 0.01597803])],
 [array([0.01668571, 0.03759392, 0.03105106, 0.04394247, 0.06411194,
         0.02567975, 0.04457805, 0.03781456]),
  array([0.0056281 , 0.01653198, 0.01099938, 0.01143043, 0.02578757,
         0.01392144, 0.01959599, 0.01597803])],
 [array([0.01668571, 0.03759392, 0.03105106, 0.04394247, 0.06411194,
         0.02567975, 0.04457805, 0.03781456]),
  array([0.0056281 , 0.01653198, 0.01099938, 0.01143043, 0.02578757,
         0.01392144, 0.01959599, 0.01597803])],
 [array([nan, nan, nan, nan, nan, nan, nan, nan]),
  array([0.00720775, 0.01954083, 0.01386391, 0.01607501, 0.03126248,
         0.0156012 , 0.02316485, 0.01909753])],
 [array([0.01668571, 0.03759392, 0.03105106, 0.04394247, 0.06411194,
         0.02567975, 0.04457805, 0.03781456]),
  array([0.005628